# Relative path to C:/Users/%USERNAME%/MRC/MRC - MI9050_Various_Benchmark/Main_Directory
# Since the username in the common path is dynamic, we use a path that is relative to the main directory.
MASTER_FILE: Alınan Veriler/2023/2.Dönem/2023_YILLIK_MASTER_DOSYA.xlsx
TEMPLATE_PATH: Sunum_Şablonları/Kıyaslama_Çalışması_Yıl_Sonu_Raporu_Template.pptx

# This section contains the mapping of company groups to their respective EDAŞ companies.
# - The key is the group name.
# - The value is a list of companies in that group.
COMPANY_GROUPS:
  MRC: []  # MRC will be used for the comparison of all companies. Therefore, it is represented as an empty list.
  AYDEM: ["ADM EDAŞ", "GDZ EDAŞ"]
  ENERJİSA: ["BAŞKENT EDAŞ", "AYEDAŞ", "TOROSLAR EDAŞ"]
  AKSA: ["FIRAT EDAŞ", "ÇORUH EDAŞ"]
  SEDAŞ: ["SEDAŞ"]
  YEDAŞ: ["YEDAŞ"]
  TREDAŞ: ["TREDAŞ"]
  VEDAŞ: ["VEDAŞ"]
  UEDAŞ: ["UEDAŞ"]
  ARAS EDAŞ: ["ARAS EDAŞ"]

# This section contains the companies that are excluded from the report.
# Note that these groups are not included in the report, but they are used for the comparison of all companies.
# Usually it is an empty list, but it can be used for debugging purposes.
COMPANY_GROUPS_EXCLUDED_FROM_REPORT: []

# Choices for years and periods
REPORT_YEAR: 2023
REPORT_TYPE: yillik  # Should be one of REPORT_TYPE_CHOICES (yariyillik, yillik)

# Sigma value for outlier detection.
# The values that are outside the range (mean - sigma * std, mean + sigma * std) are considered as outliers.
SIGMA: 3

# Presentation pages and annotation offset settings
PRESENTATION_PAGES: [0, 1, 2, 3, 17, 21, 25, 42, 68, 84, 103]
ANNOTATION_OFFSET_PIXELS: [-5, 5]

# Plot appearance settings
HORIZONTAL_MEAN_COLOR: purple
HORIZONTAL_MEAN_ALPHA: 0.7
FONT_SIZE: 10.5
